substitutions:
  name: kp2
  friendly_name: Keuken Plafond 02
packages:
  athom.rgbww-light: github://roblan123/athom-configs/athom-rgbww-light.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
api:
  password: !secret wifi_password
 
ota:
  password: !secret wifi_password
