substitutions:
  name: "sonoff-sw03"
  friendly_name: "rob SW03"
  project_name: "rob.sw03"
  project_version: "1.0"
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:

ota:

logger:
  baud_rate: 0

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://roblan123/athom/sonoff-sw03.yaml



binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} Touchpad 1"
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} Touchpad 2"
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${friendly_name} Touchpad 3"
  - platform: status
    name: "Sonoff T1 UK 3 Gang Status"

switch:
  - platform: gpio
    name: "${friendly_name} Switch 1"
    pin: GPIO12
  - platform: gpio
    name: "${friendly_name} Switch 2"
    pin: GPIO5
  - platform: gpio
    name: "${friendly_name} Switch 3"
    pin: GPIO4

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${friendly_name} Blue LED"
    output: blue_led
