substitutions:
  name: "sonoff-sw03"
  friendly_name: "sonoff SW03"
  project_name: "sonoff.sw03"
  project_version: "1.0"
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:

ota:

logger:
  baud_rate: 0

web_server:
  port: 80

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

captive_portal:

dashboard_import:
  package_import_url: github://roblan123/athom/sonoff-sw03.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO0
    name: "${friendly_name} Button 1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button
  - platform: gpio
    pin:
      inverted: true
      number: GPIO9
    name: "${friendly_name} Button 2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2
  - platform: gpio
    pin:
      inverted: true
      number: GPIO10
    name: "${friendly_name} Button 3"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"

output:
  # Relays
  - platform: gpio
    pin: GPIO12
    id: relay1
  - platform: gpio
    pin: GPIO5
    id: relay2
  - platform: gpio
    pin: GPIO3
    id: relay3

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO16
    inverted: true
    id: button_led1
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: button_led2
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: button_led3

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "${friendly_name} Light 1"
    id: light1
    output: relay1
    restore_mode: ${light1_restore_mode}
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1
  - platform: binary
    name: "${friendly_name} Light 2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}
    on_turn_on:
      - light.turn_on: led2
    on_turn_off:
      - light.turn_off: led2
  - platform: binary
    name: "${friendly_name} Light 3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}
    on_turn_on:
      - light.turn_on: led3
    on_turn_off:
      - light.turn_off: led3

  # Button LEDs
  - platform: monochromatic
    name: "${friendly_name} LED1"
    disabled_by_default: true
    id: led1
    output: button_led1
    default_transition_length: 500ms
  - platform: monochromatic
    name: "${friendly_name} LED2"
    disabled_by_default: true
    id: led2
    output: button_led2
    default_transition_length: 500ms
  - platform: monochromatic
    name: "${friendly_name} LED3"
    disabled_by_default: true
    id: led3
    output: button_led3
    default_transition_length: 500ms


text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true
