substitutions:
  name: wkp4
  friendly_name: Woonkamer Plafond 04
packages:
  athom.rgbww-light: github://roblan123/athom-configs/athom-rgbww-light.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  password: !secret wifi_password
 
ota:
  password: !secret wifi_password
